#! / bin / bash
CD
se [ $ ( id -u )  ! = 0]
então
echo  " Execute o script como root "
Saída
fi
echo -e " \ 033 [1; 30mInstalando ... \ 033 [0m "
mkdir / etc / VpsPackdir 2> / dev / null
mkdir / etc / VpsPackdir / limite 2> / dev / null
mkdir / etc / VpsPackdir / senha 2> / dev / null
rm -rf / bin / limite 2> / dev / null
wget -o / dev / null -O- https://raw.githubusercontent.com/RicKbrL/VpsPack/master/limite > / bin / limite
chmod + x / bin / limite
rm -rf / bin / criarusuario 2> / dev / null
wget -o / dev / null -O- https://raw.githubusercontent.com/RicKbrL/VpsPack/master/criarusuario > / bin / créerusuario
Chmod + x / bin / créerusuario
rm -rf / bin / deletarusuario 2> / dev / null
wget -o / dev / null -O- https://raw.githubusercontent.com/RicKbrL/VpsPack/master/deletarusuario > / bin / deletarusuario
Chmod + x / bin / deletarusuario
rm -rf / bin / redefinirusuario 2> / dev / null
wget -o / dev / null -O- https://raw.githubusercontent.com/RicKbrL/VpsPack/master/redefinirusuario > / bin / redefinirusuario
chmod + x / bin / redefinirusuario
rm -rf / bin / vpspack 2> / dev / null
wget -o / dev / null -O- https://raw.githubusercontent.com/RicKbrL/VpsPack/master/vpspack > / bin / vpspack
Chmod + x / bin / vpspack
rm -rf /bin/speedtest.py 2> / dev / null
wget -o / dev / null -O- https://raw.githubusercontent.com/RicKbrL/VpsPack/master/speedtest.py > /bin/speedtest.py
Chmod + x /bin/speedtest.py
Claro
echo -e " \ 033 [1; 32mInstalação concluida \ n \ 033 [1; 30mExecute: "
echo -e " \ n \ 033 [1; 32mvpspack \ 033 [1; 30mMenu com opcoes "
echo -e " \ 033 [1; 32mcriarusuario \ 033 [1; 30mCriar usuário com dados e limite "
echo -e " \ 033 [1; 32mdeletarusuario \ 033 [1; 30mDeletar usuário ou apenas desconectar "
echo -e " \ 033 [1; 32mredefinirusuario \ 033 [1; 30mAlterar dados, senha, etc., de um usuário "
echo -e " \ 033 [1; 32mlimite \ 033 [1; 30mLimite de logins simultaneos \ 033 [0m "
rm -rf install
