#! / bin / bash
userrc = $ ( echo $ 1  | sed ' s / @ / aa / g '  | sed ' s / - / k / g '  | sed ' s / 0 / a / g '  | sed ' s / 1 / b / g '  | sed ' s / 2 / c / g '  | sed ' s / 3 / d / g '  | sed ' s / 4 / e / g '  | sed ' s / 5 / f / g '  | sed ' s / 6 / g / g '  | sed 's / 7 / h / g ' | sed ' s / 8 / i / g '  | sed ' s / 9 / j / g ' )
limpcron = $ ( cat / etc / crontab | grep -v " # $ 1 # " )
Echo  " $ limpcron "  > / etc / crontab
echo  " #! / bin / sh
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
durma 2,5s
se [ \ $ (ps -u $ 1 | grep sshd | wc -l) -gt $ 2 ]; então ps -u $ 1 | grep sshd | awk '{print \ $ 1}'> / tmp / sshpid $ 1 ; sshpid $ userrc = \ $ (cat -n / tmp / sshpid $ 1 | awk ' \ $ 1> $ 2 {print \ $ 2}'); mata \ $ sshpid $ userrc ; fi
Saída
"  > / etc / VpsPackdir / limite / $ 1 .sh
Chmod a + x / etc / VpsPackdir / limite / $ 1 .sh 2> / dev / null
echo  " * / 1 * * * * root / etc / VpsPackdir / limite / $ 1 .sh # $ 1 # "  >> / etc / crontab
echo -e " \ 033 [1; 37mUsuario: \ 033 [1; 31m [\ 033 [1; 37m $ 1 \ 033 [1; 31m] \ 033 [1; 37m Limite: \ 033 [1; 31m [\ 033 [ 1; 37m $ 2 \ 033 [1; 31m] \ 033 [1; 37m [\ 033 [1; 31mLimite Aplicado \ 033 [1; 37m] \ 033 [0m " 
Echo  " $ 2 "  > / etc / VpsPackdir / limite / $ 1
